---
- hosts: all
  become: yes

  pre_tasks:
    - name: "Set env variables"
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^export {{ item.var }}="
        line: "export {{ item.var }}={{ item.value }}"
      with_items:
        - { var: "RACK_ENV", value: "development" }
        - { var: "LC_ALL", value: "en_US.UTF-8" }

    - name: Install apt packages
      apt:
        name: '{{ item }}'
        update_cache: yes
      with_items:
        - zlib1g-dev
        - liblzma-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - software-properties-common
        - libffi-dev
        - git-core 
        - curl 
        
    - name: Add autofollow
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^cd /vagrant"
        line: "cd /vagrant"

  post_tasks:
    - name: 'Install rails dependencies'
      apt:
        name: '{{ item }}'
        update_cache: yes
      with_items:
        - ruby2.5-dev
                  
    - name: 'Install gem rails'
      gem:
        name: rails
        state: latest
        user_install: no

  roles:
    - role: ntp
    - role: ruby-brightbox
    - role: postgresql

