- src: https://github.com/geerlingguy/ansible-role-ntp
  name: ntp

- src: https://github.com/vterdunov/ansible-ruby-brightbox
  name: ruby-brightbox

- src: geerlingguy.postgresql
  name: postgresql
